# Generated by Django 3.0.3 on 2020-03-02 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '类别'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '博客信息'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签'},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 10, 6, 44, 26342)),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 10, 6, 44, 26363)),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
